// caseAgents.js — Stage automation engine for case management
// Triggers actions (letter generation, deadlines, record requests) when a case moves stages.

const API_BASE = "https://tools.sherlawgroup.com";

// ─── Helpers ─────────────────────────────────────────────────

/**
 * Authenticated fetch to the backend API.
 */
async function agentApiFetch(path, options = {}) {
  const token = typeof getIdToken === "function" ? await getIdToken() : null;
  const url = path.startsWith("http") ? path : `${API_BASE}${path}`;
  const resp = await fetch(url, {
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...options.headers,
    },
  });
  if (!resp.ok) {
    const body = await resp.text();
    throw new Error(`API ${resp.status}: ${body}`);
  }
  if (resp.status === 204) return null;
  return resp.json();
}

/**
 * Call Claude API to generate a document draft.
 * Returns the text content of the response.
 */
async function generateWithClaude(systemPrompt, userMessage) {
  const apiKey =
    typeof getClaudeApiKey === "function" ? getClaudeApiKey() : null;
  if (!apiKey) throw new Error("Claude API key not configured");

  const resp = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "anthropic-dangerous-direct-browser-access": "true",
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: 4096,
      system: systemPrompt,
      messages: [{ role: "user", content: userMessage }],
    }),
  });

  if (!resp.ok) {
    const body = await resp.text();
    throw new Error(`Claude API ${resp.status}: ${body}`);
  }

  const data = await resp.json();
  return data.content?.[0]?.text || "";
}

/**
 * Save a generated document to the backend.
 */
async function saveDocument(caseId, title, content, docType) {
  return agentApiFetch("/api/case-documents", {
    method: "POST",
    body: JSON.stringify({ caseId, title, content, docType }),
  });
}

/**
 * Trigger auto-generated deadlines for a given stage.
 */
async function autoGenerateDeadlines(caseId, stage) {
  return agentApiFetch("/api/deadlines/auto-generate", {
    method: "POST",
    body: JSON.stringify({ caseId, stage }),
  });
}

/**
 * Look up a case by ID from local storage.
 */
function getCase(caseId) {
  const cases = loadCases();
  const c = cases.find((x) => x.id === caseId);
  if (!c) throw new Error(`Case ${caseId} not found`);
  return c;
}

// ─── Stage Handlers ──────────────────────────────────────────

/**
 * INTAKE — Create OneDrive folder structure for the new case.
 */
async function handleIntake(caseId) {
  const c = getCase(caseId);
  const clientName = c.clientName || c.name || "Unknown Client";
  const caseType = c.caseType || c.type || "General";
  const folderName = `${clientName} - ${caseType}`;
  const basePath = `/me/drive/root:/Cases/${folderName}:`;

  // Create the root case folder first
  await graphFetch("/me/drive/root:/Cases:/children", {
    method: "POST",
    body: JSON.stringify({ name: folderName, folder: {} }),
  });

  const subfolders = [
    "Intake",
    "Correspondence",
    "Medical Records",
    "Settlement",
    "Liens",
    "Health Insurance",
    "Police Report",
    "Demand",
  ];

  const results = await Promise.allSettled(
    subfolders.map((name) =>
      graphFetch(`${basePath}/children`, {
        method: "POST",
        body: JSON.stringify({ name, folder: {} }),
      })
    )
  );

  const failed = results.filter((r) => r.status === "rejected");
  if (failed.length > 0) {
    console.warn(
      `[caseAgents] ${failed.length} subfolder(s) failed to create:`,
      failed.map((r) => r.reason?.message)
    );
  }

  showToast(
    `OneDrive folder created: Cases/${escapeHtml(folderName)}`,
    "success"
  );
}

/**
 * LOR_SENT — Generate Letters of Representation and create deadlines.
 */
async function handleLorSent(caseId) {
  const c = getCase(caseId);
  const clientName = c.clientName || c.name || "Unknown Client";
  const dateOfLoss = c.dateOfIncident || c.dateOfLoss || "N/A";
  const claimNumber = c.claimNumber || "N/A";

  const lorSystemPrompt = `You are a paralegal AI assistant at Sher Law Group, a personal injury law firm in Arizona. Draft a professional Letter of Representation (LOR). The letter should:
- Use Sher Law Group letterhead format (firm name, address placeholder)
- Be addressed from the attorney at Sher Law Group
- State that the firm has been retained to represent the client regarding their personal injury claim
- Reference the date of loss and claim number
- Request all future communications be directed to the firm
- Note that a HIPAA authorization is enclosed for release of medical records and billing
- Include standard Arizona personal injury LOR language
- Request preservation of all evidence including surveillance footage
- Be formal, professional, and concise
- End with a professional closing and signature block`;

  // Letter to at-fault insurance carrier
  const atFaultCarrier = c.insuranceCompany || c.atFaultCarrier || "Unknown Carrier";
  const adjusterName = c.adjusterName || "Claims Department";
  const adjusterInfo = c.adjusterEmail
    ? `${adjusterName} (${c.adjusterEmail})`
    : adjusterName;

  const atFaultPrompt = `Draft a Letter of Representation to the at-fault party's insurance carrier with the following details:

Recipient: ${adjusterInfo}
Insurance Company: ${atFaultCarrier}
Claim Number: ${claimNumber}
Client Name: ${clientName}
Date of Loss: ${dateOfLoss}
Case Type: ${c.caseType || c.type || "Personal Injury"}

This letter is being sent to the at-fault party's insurer. Include language directing all communication to the firm, requesting claim information, and noting the enclosed HIPAA authorization.`;

  // Letter to client's own auto carrier (UM/UIM / MedPay)
  const clientCarrier = c.clientInsuranceCompany || c.clientCarrier || "Client's Auto Carrier";
  const clientPolicyNumber = c.clientPolicyNumber || "N/A";

  const clientCarrierPrompt = `Draft a Letter of Representation to the client's own automobile insurance carrier with the following details:

Recipient: Claims Department
Insurance Company: ${clientCarrier}
Policy Number: ${clientPolicyNumber}
Client Name: ${clientName}
Date of Loss: ${dateOfLoss}
Case Type: ${c.caseType || c.type || "Personal Injury"}

This letter is being sent to the client's own auto carrier to put them on notice of a potential UM/UIM or MedPay claim. Include language directing all communication to the firm, requesting policy declarations and limits information, and noting the enclosed HIPAA authorization.`;

  // Generate both letters in parallel
  const [atFaultLetter, clientCarrierLetter] = await Promise.all([
    generateWithClaude(lorSystemPrompt, atFaultPrompt),
    generateWithClaude(lorSystemPrompt, clientCarrierPrompt),
  ]);

  // Save both letters and create deadlines in parallel
  await Promise.all([
    saveDocument(
      caseId,
      `LOR - ${atFaultCarrier}`,
      atFaultLetter,
      "lor_at_fault"
    ),
    saveDocument(
      caseId,
      `LOR - ${clientCarrier}`,
      clientCarrierLetter,
      "lor_client_carrier"
    ),
    autoGenerateDeadlines(caseId, "lor_sent"),
  ]);

  showToast("Letters of Representation generated and deadlines created", "success");
}

/**
 * DEMAND_SENT — Create response deadlines.
 */
async function handleDemandSent(caseId) {
  await autoGenerateDeadlines(caseId, "demand_sent");
  showToast("Demand response deadlines created", "success");
}

/**
 * LITIGATION_FILED — Generate complaint draft.
 */
async function handleLitigationFiled(caseId) {
  const c = getCase(caseId);
  const clientName = c.clientName || c.name || "Unknown Client";
  const dateOfLoss = c.dateOfIncident || c.dateOfLoss || "N/A";

  const systemPrompt = `You are a paralegal AI assistant at Sher Law Group, a personal injury law firm in Arizona. Draft a Complaint for filing in Arizona Superior Court. Follow Arizona Rules of Civil Procedure formatting. Include:
- Caption with court name (Maricopa County Superior Court), case number placeholder
- Parties section identifying plaintiff and defendant(s)
- Jurisdiction and venue paragraphs
- Factual allegations regarding the incident
- Counts for negligence and any applicable theories of liability
- Damages allegations (general, special, punitive if applicable)
- Prayer for relief
- Jury demand
- Attorney signature block for Sher Law Group
Use formal legal pleading language and proper paragraph numbering.`;

  const userPrompt = `Draft a Complaint based on the following case information:

Plaintiff: ${clientName}
Date of Incident: ${dateOfLoss}
Case Type: ${c.caseType || c.type || "Personal Injury"}
Defendant: ${c.defendantName || c.atFaultParty || "Unknown Defendant"}
Location of Incident: ${c.incidentLocation || c.location || "Maricopa County, Arizona"}
Summary of Facts: ${c.caseSummary || c.notes || "Personal injury arising from negligence of the defendant."}
Injuries: ${c.injuries || "To be detailed based on medical records."}`;

  const complaint = await generateWithClaude(systemPrompt, userPrompt);

  await saveDocument(caseId, "Complaint - DRAFT", complaint, "complaint");

  showToast("Complaint draft generated", "success");
}

/**
 * LITIGATION_SERVED — Create service-related deadlines.
 */
async function handleLitigationServed(caseId) {
  await autoGenerateDeadlines(caseId, "litigation_served");
  showToast("Service deadlines created", "success");
}

/**
 * LITIGATION_ANSWERED — Create answer-related deadlines and generate Initial Disclosure Statement.
 */
async function handleLitigationAnswered(caseId) {
  const c = getCase(caseId);
  const clientName = c.clientName || c.name || "Unknown Client";
  const dateOfLoss = c.dateOfIncident || c.dateOfLoss || "N/A";

  const systemPrompt = `You are a paralegal AI assistant at Sher Law Group, a personal injury law firm in Arizona. Draft an Initial Disclosure Statement pursuant to Arizona Rule of Civil Procedure 26.1. Include:
- Caption with court name and case number placeholder
- Statement of factual basis for claims
- Legal theories upon which claims are based
- Names, addresses, and telephone numbers of witnesses with summary of expected testimony
- List of documents relevant to the action (to be supplemented)
- Computation of damages
- Copies of relevant insurance agreements (referenced)
- Certification and signature block
Follow the required format under ARCP Rule 26.1.`;

  const userPrompt = `Draft an Initial Disclosure Statement for the following case:

Plaintiff: ${clientName}
Date of Incident: ${dateOfLoss}
Case Type: ${c.caseType || c.type || "Personal Injury"}
Defendant: ${c.defendantName || c.atFaultParty || "Unknown Defendant"}
Summary of Facts: ${c.caseSummary || c.notes || "Personal injury arising from negligence of the defendant."}
Injuries: ${c.injuries || "To be detailed based on medical records."}
Treating Providers: ${c.treatingProviders || "To be supplemented."}`;

  const [disclosure] = await Promise.all([
    generateWithClaude(systemPrompt, userPrompt),
    autoGenerateDeadlines(caseId, "litigation_answered"),
  ]);

  await saveDocument(
    caseId,
    "Initial Disclosure Statement - DRAFT",
    disclosure,
    "initial_disclosure"
  );

  showToast(
    "Initial Disclosure Statement drafted and deadlines created",
    "success"
  );
}

/**
 * SETTLED — Generate lien reduction letters for providers with outstanding balances.
 */
async function handleSettled(caseId) {
  const c = getCase(caseId);
  const clientName = c.clientName || c.name || "Unknown Client";

  // Fetch specials (medical providers/billing)
  const specials = await agentApiFetch(`/api/specials?caseId=${caseId}`);
  const providers = Array.isArray(specials) ? specials : specials?.items || [];

  // Filter to providers with outstanding balances
  const outstanding = providers.filter(
    (p) => p.outstandingBalance > 0 || p.balance > 0 || p.amountOwed > 0
  );

  if (outstanding.length === 0) {
    showToast("No outstanding provider balances found — no reduction letters needed", "info");
    return;
  }

  const systemPrompt = `You are a paralegal AI assistant at Sher Law Group, a personal injury law firm in Arizona. Draft a professional lien reduction request letter to a medical provider. The letter should:
- Be on Sher Law Group letterhead format
- Reference the client's personal injury case
- State the total medical charges from the provider
- Explain that the case has settled and request a reduction in the outstanding balance
- Note that the reduction will facilitate resolution and timely payment
- Be respectful and professional while advocating for the client
- Include a signature block for the attorney at Sher Law Group
- Request a response within 30 days`;

  // Generate all reduction letters in parallel
  const letterPromises = outstanding.map(async (provider) => {
    const providerName = provider.providerName || provider.name || "Provider";
    const totalCharges =
      provider.totalCharges || provider.billedAmount || provider.amount || 0;
    const outstandingAmt =
      provider.outstandingBalance || provider.balance || provider.amountOwed || 0;

    const userPrompt = `Draft a lien reduction letter for the following:

Client: ${clientName}
Provider: ${providerName}
Total Charges: $${Number(totalCharges).toLocaleString("en-US", { minimumFractionDigits: 2 })}
Outstanding Balance: $${Number(outstandingAmt).toLocaleString("en-US", { minimumFractionDigits: 2 })}
Settlement Status: Case has been settled.

Request a reasonable reduction of the outstanding balance to facilitate prompt payment.`;

    const letter = await generateWithClaude(systemPrompt, userPrompt);

    await saveDocument(
      caseId,
      `Reduction Letter - ${providerName}`,
      letter,
      "reduction_letter"
    );

    return providerName;
  });

  const results = await Promise.allSettled(letterPromises);
  const succeeded = results.filter((r) => r.status === "fulfilled").length;
  const failed = results.filter((r) => r.status === "rejected").length;

  if (failed > 0) {
    showToast(
      `Reduction letters: ${succeeded} generated, ${failed} failed`,
      "warning"
    );
  } else {
    showToast(
      `${succeeded} lien reduction letter(s) generated`,
      "success"
    );
  }
}

// ─── Main Dispatcher ─────────────────────────────────────────

/**
 * Stage-handler dispatch map.
 */
const STAGE_HANDLERS = {
  fee_agreement_sent: handleFeeAgreementSent,
  lor_sent: handleLorSent,
  demand_sent: handleDemandSent,
  litigation_filed: handleLitigationFiled,
  litigation_served: handleLitigationServed,
  litigation_answered: handleLitigationAnswered,
  settled: handleSettled,
};

/**
 * Called whenever a case moves to a new stage.
 * Dispatches to the appropriate handler without blocking the UI.
 *
 * @param {string} caseId
 * @param {string} oldStage
 * @param {string} newStage
 */
function onStageChange(caseId, oldStage, newStage) {
  const handler = STAGE_HANDLERS[newStage];
  if (!handler) return;

  console.log(
    `[caseAgents] Stage change: ${oldStage} → ${newStage} (case ${caseId})`
  );

  // Fire-and-forget — runs async without blocking the caller
  handler(caseId).catch((err) => {
    console.error(`[caseAgents] Error in ${newStage} handler:`, err);
    showToast(`Stage automation error: ${err.message}`, "error");
  });
}

/**
 * FEE_AGREEMENT_SENT — No auto-action needed (case sits here waiting for signature).
 */
async function handleFeeAgreementSent(caseId) {
  // Placeholder: when Adobe Sign is wired up, this will poll for signature status
  showToast("Waiting for fee agreement signature...", "info");
}

/**
 * Called when a new case is created. Handles intake automation:
 * 1. Create OneDrive folder structure
 * 2. Auto-populate fee agreement and prompt to send
 *
 * @param {string} caseId
 */
function onCaseCreate(caseId) {
  console.log(`[caseAgents] New case created: ${caseId}`);

  // OneDrive folder creation (fire-and-forget)
  handleIntake(caseId).catch((err) => {
    console.error("[caseAgents] Error in intake handler:", err);
    showToast(`Intake automation error: ${err.message}`, "error");
  });

  // Prompt user to send fee agreement
  const c = getCase(caseId);
  showToast(`New case: ${c.clientName} — click the case card to send fee agreement`, "info");
}
